Add box update and stronger destroyall

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -14,6 +14,11 @@ validate:
   script:
     - vagrant validate
 
+update:
+  stage: update
+  script:
+    - vagrant box update
+
 build:
   stage: build
   script:
@@ -80,11 +85,16 @@ destroyall:
         vagrant destroy --force "${name}"
       done <<< $(vagrant status --machine-readable | awk 'BEGIN { FS = "," } ; { if ($3 == "metadata") { print $2 }}')
     - sleep 30
+    # Clean up any VMs that Vagrant lost
     - |
       while read -r name; do
         echo "Destroying VM ${name}"
-        vboxmanage unregistervm --delete "${name}"
+        vboxmanage unregistervm --delete "${name}" || true
       done <<< $(vboxmanage list vms | cut -d'"' -f2)
+    # Clean up an VMs that VirtualBox lost
+    - killall -9 VBoxHeadless || true
+    # Deleting any remaining VM state
+    - rm -rf ~/Virtualbox\ VMs/*
   when: manual
   only:
     - master
